<form action="/users" method="get">
    <input type="search" name="userName" />
    <input type="submit" value="Search" />

    <div>
        <label>
            <input type="text" name="user[name]" >
        </label>
    </div>
    <div>
        <label>
            Email
            <input type="email" required name="user[email]" >
        </label>
    </div>

    <input type="submit" value="Sign Up">
</form>
